import { Genre } from '@/types';

export const GENRES: Genre[] = [
  // Electronic
  {
    id: 'vaporwave',
    name: 'Vaporwave',
    subreddit: 'Vaporwave',
    description: 'Aesthetic electronic music with 80s/90s samples',
    icon: '🌴',
    color: '#ff71ce',
    category: 'Electronic',
  },
  {
    id: 'synthwave',
    name: 'Synthwave',
    subreddit: 'synthwave',
    description: 'Retro 80s inspired electronic music',
    icon: '🌆',
    color: '#01cdfe',
    category: 'Electronic',
  },
  {
    id: 'lofi',
    name: 'Lo-Fi Hip Hop',
    subreddit: 'LofiHipHop',
    description: 'Chill beats to relax/study to',
    icon: '☕',
    color: '#b967ff',
    category: 'Electronic',
  },
  {
    id: 'chillwave',
    name: 'Chillwave',
    subreddit: 'chillwave',
    description: 'Dreamy, nostalgic electronic pop',
    icon: '🌊',
    color: '#fffb96',
    category: 'Electronic',
  },
  {
    id: 'electronicmusic',
    name: 'Electronic',
    subreddit: 'electronicmusic',
    description: 'All genres of electronic music',
    icon: '⚡',
    color: '#05ffa1',
    category: 'Electronic',
  },
  {
    id: 'futurebeats',
    name: 'Future Beats',
    subreddit: 'futurebeats',
    description: 'Experimental electronic and hip-hop',
    icon: '🔮',
    color: '#ff6b6b',
    category: 'Electronic',
  },
  {
    id: 'idm',
    name: 'IDM',
    subreddit: 'IDM',
    description: 'Intelligent Dance Music',
    icon: '🧠',
    color: '#9b59b6',
    category: 'Electronic',
  },
  {
    id: 'dnb',
    name: 'Drum & Bass',
    subreddit: 'DnB',
    description: 'High-energy drum and bass music',
    icon: '🥁',
    color: '#e67e22',
    category: 'Electronic',
  },
  {
    id: 'techno',
    name: 'Techno',
    subreddit: 'Techno',
    description: 'Electronic dance music',
    icon: '🔊',
    color: '#9b59b6',
    category: 'Electronic',
  },
  {
    id: 'dubtechno',
    name: 'Dub Techno',
    subreddit: 'dubtechno',
    description: 'Dub techno and experimental electronic',
    icon: '🌌',
    color: '#34495e',
    category: 'Electronic',
  },
  {
    id: 'chiptune',
    name: 'Chiptune',
    subreddit: 'chiptune',
    description: 'Retro video game music and chip tunes',
    icon: '🎮',
    color: '#ffd32a',
    category: 'Electronic',
  },
  {
    id: 'house',
    name: 'House',
    subreddit: 'house',
    description: 'House music and its subgenres',
    icon: '🎧',
    color: '#ff9f43',
    category: 'Dance & Club',
  },
  {
    id: 'dubstep',
    name: 'Dubstep',
    subreddit: 'dubstep',
    description: 'Heavy bass and dubstep tracks',
    icon: '💥',
    color: '#d63031',
    category: 'Dance & Club',
  },
  {
    id: 'trap',
    name: 'Trap',
    subreddit: 'trap',
    description: 'Trap beats and modern hip hop production',
    icon: '🎯',
    color: '#e84393',
    category: 'Hip Hop',
  },
  {
    id: 'edm',
    name: 'EDM',
    subreddit: 'EDM',
    description: 'Electronic Dance Music',
    icon: '🎶',
    color: '#00b894',
    category: 'Dance & Club',
  },

  // Discovery / Curated
  {
    id: 'listentothis',
    name: 'Listen To This',
    subreddit: 'listentothis',
    description: 'Discover new and overlooked music',
    icon: '🎵',
    color: '#4ecdc4',
    category: 'Discovery',
  },
  {
    id: 'music',
    name: 'Music',
    subreddit: 'Music',
    description: 'General music discovery and discussions',
    icon: '🎧',
    color: '#00a8ff',
    category: 'Discovery',
  },

  // Rock & Alternative
  {
    id: 'indieheads',
    name: 'Indie',
    subreddit: 'indieheads',
    description: 'Indie rock and alternative music',
    icon: '🎸',
    color: '#f7dc6f',
    category: 'Rock',
  },
  {
    id: 'alternative',
    name: 'Alternative',
    subreddit: 'alternative',
    description: 'Alternative rock and modern rock',
    icon: '🎸',
    color: '#f19066',
    category: 'Rock',
  },
  {
    id: 'grunge',
    name: 'Grunge',
    subreddit: 'grunge',
    description: '90s grunge and alternative rock',
    icon: '🪨',
    color: '#6c5ce7',
    category: 'Rock',
  },
  {
    id: 'progrock',
    name: 'Progressive Rock',
    subreddit: 'progrock',
    description: 'Progressive rock and complex compositions',
    icon: '🎹',
    color: '#e17055',
    category: 'Rock',
  },
  {
    id: 'shoegaze',
    name: 'Shoegaze',
    subreddit: 'shoegaze',
    description: 'Dreamy, effects-heavy alternative rock',
    icon: '🌫️',
    color: '#74b9ff',
    category: 'Rock',
  },
  {
    id: 'postrock',
    name: 'Post-Rock',
    subreddit: 'postrock',
    description: 'Experimental and atmospheric rock',
    icon: '🎻',
    color: '#34495e',
    category: 'Rock',
  },
  {
    id: 'punk',
    name: 'Punk',
    subreddit: 'punk',
    description: 'Punk rock and its subgenres',
    icon: '💀',
    color: '#c0392b',
    category: 'Rock',
  },
  {
    id: 'emo',
    name: 'Emo',
    subreddit: 'emo',
    description: 'Emotional rock and emo music',
    icon: '😢',
    color: '#e74c3c',
    category: 'Rock',
  },
  {
    id: 'screamo',
    name: 'Screamo',
    subreddit: 'screamo',
    description: 'Intense screamo and hardcore',
    icon: '😱',
    color: '#c0392b',
    category: 'Rock',
  },
  {
    id: 'metal',
    name: 'Metal',
    subreddit: 'Metal',
    description: 'Heavy metal in all its forms',
    icon: '🤘',
    color: '#8e44ad',
    category: 'Rock',
  },

  // Hip Hop & Rap
  {
    id: 'hiphopheads',
    name: 'Hip Hop',
    subreddit: 'hiphopheads',
    description: 'Hip hop music and culture',
    icon: '🎤',
    color: '#e74c3c',
    category: 'Hip Hop',
  },
  {
    id: 'rap',
    name: 'Rap',
    subreddit: 'rap',
    description: 'Rap music and lyricism-focused content',
    icon: '🎤',
    color: '#ff7675',
    category: 'Hip Hop',
  },
  {
    id: 'conscioushiphop',
    name: 'Conscious Hip Hop',
    subreddit: 'conscioushiphop',
    description: 'Conscious and political hip hop',
    icon: '✊',
    color: '#fdcb6e',
    category: 'Hip Hop',
  },
  {
    id: 'undergroundrap',
    name: 'Underground Rap',
    subreddit: 'undergroundrap',
    description: 'Underground and independent rap',
    icon: '🕳️',
    color: '#2d3436',
    category: 'Hip Hop',
  },

  // World & Regional
  {
    id: 'worldmusic',
    name: 'World Music',
    subreddit: 'worldmusic',
    description: 'Global music from various cultures',
    icon: '🌍',
    color: '#00cec9',
    category: 'World',
  },
  {
    id: 'afrobeats',
    name: 'Afrobeats',
    subreddit: 'afrobeats',
    description: 'African beats and modern African music',
    icon: '🪘',
    color: '#ff9ff3',
    category: 'World',
  },
  {
    id: 'kpop',
    name: 'K-Pop',
    subreddit: 'kpop',
    description: 'K-pop music and culture',
    icon: '💜',
    color: '#9b59b6',
    category: 'Pop',
  },
  {
    id: 'latinmusic',
    name: 'Latin',
    subreddit: 'latinmusic',
    description: 'Latin music (reggaeton, salsa, bachata)',
    icon: '🪗',
    color: '#ffbe76',
    category: 'World',
  },

  // Pop, R&B & Country
  {
    id: 'pop',
    name: 'Pop',
    subreddit: 'pop',
    description: 'Pop music and chart-topping hits',
    icon: '🎤',
    color: '#ff6b6b',
    category: 'Pop',
  },
  {
    id: 'rnb',
    name: 'R&B',
    subreddit: 'rnb',
    description: 'R&B and contemporary R&B',
    icon: '💿',
    color: '#6c5ce7',
    category: 'Pop',
  },
  {
    id: 'country',
    name: 'Country',
    subreddit: 'country',
    description: 'Country music and folk-country',
    icon: '🤠',
    color: '#e1b12c',
    category: 'Folk & Country',
  },

  // Niche / Aesthetic
  {
    id: 'futurefunk',
    name: 'Future Funk',
    subreddit: 'futurefunk',
    description: 'Future funk and vaporwave-adjacent electronic',
    icon: '🕺',
    color: '#ffbe76',
    category: 'Electronic',
  },
  {
    id: 'mallsoft',
    name: 'Mallsoft',
    subreddit: 'mallsoft',
    description: 'Mallsoft and elevator music aesthetics',
    icon: '🛍️',
    color: '#f6e58d',
    category: 'Electronic',
  },
  {
    id: '80s',
    name: '80s',
    subreddit: '80s',
    description: '80s music nostalgia',
    icon: '📼',
    color: '#f8a5c2',
    category: 'Era',
  },
  {
    id: '90s',
    name: '90s',
    subreddit: '90s',
    description: '90s music and alternative rock',
    icon: '💿',
    color: '#c7ecee',
    category: 'Era',
  },
  {
    id: 'soundtracks',
    name: 'Soundtracks',
    subreddit: 'soundtracks',
    description: 'Movie and game soundtracks',
    icon: '🎬',
    color: '#6ab04c',
    category: 'Discovery',
  },

  // Live / Production
  {
    id: 'concerts',
    name: 'Concerts',
    subreddit: 'concerts',
    description: 'Concert discussions and live music',
    icon: '🎟️',
    color: '#30336b',
    category: 'Live & Production',
  },
  {
    id: 'WeAreTheMusicMakers',
    name: 'We Are The Music Makers',
    subreddit: 'WeAreTheMusicMakers',
    description: 'Music production and behind-the-scenes',
    icon: '🔧',
    color: '#5352ed',
    category: 'Live & Production',
  },

  // Traditional genres
  {
    id: 'jazz',
    name: 'Jazz',
    subreddit: 'Jazz',
    description: 'Jazz music from all eras',
    icon: '🎷',
    color: '#3498db',
    category: 'Traditional',
  },
  {
    id: 'ambient',
    name: 'Ambient',
    subreddit: 'ambientmusic',
    description: 'Atmospheric and ambient soundscapes',
    icon: '🌙',
    color: '#1abc9c',
    category: 'Traditional',
  },
  {
    id: 'folk',
    name: 'Folk',
    subreddit: 'folk',
    description: 'Folk music and acoustic songs',
    icon: '🎶',
    color: '#f39c12',
    category: 'Folk & Country',
  },
  {
    id: 'classical',
    name: 'Classical',
    subreddit: 'classicalmusic',
    description: 'Classical and orchestral music',
    icon: '🎼',
    color: '#3498db',
    category: 'Traditional',
  },
  {
    id: 'blues',
    name: 'Blues',
    subreddit: 'blues',
    description: 'Blues music and guitar legends',
    icon: '🎸',
    color: '#2c3e50',
    category: 'Traditional',
  },
  {
    id: 'reggae',
    name: 'Reggae',
    subreddit: 'reggae',
    description: 'Island rhythms and reggae music',
    icon: '🌿',
    color: '#27ae60',
    category: 'Reggae & Dub',
  },
  {
    id: 'dub',
    name: 'Dub',
    subreddit: 'dub',
    description: 'Dub music and remixes',
    icon: '🔊',
    color: '#8e44ad',
    category: 'Reggae & Dub',
  },

];

export const DEFAULT_GENRE = GENRES[0];

export const SORT_OPTIONS = [
  { value: 'hot', label: 'Hot' },
  { value: 'new', label: 'New' },
  { value: 'top', label: 'Top' },
  { value: 'rising', label: 'Rising' },
] as const;

export const TIME_FILTERS = [
  { value: 'hour', label: 'Hour' },
  { value: 'day', label: 'Day' },
  { value: 'week', label: 'Week' },
  { value: 'month', label: 'Month' },
  { value: 'year', label: 'Year' },
  { value: 'all', label: 'All Time' },
] as const;
